services:
  - type: web
    name: ecommerce-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn Eshop.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: ALLOWED_HOSTS
        value: mobile-phone-e-commerce-website.onrender.com
      - key: DEBUG
        value: "0"
      - key: DJANGO_SETTINGS_MODULE
        value: Eshop.settings
